### ISSUE TITLE
StreamRendering not working from Visual Studio

### ISSUE THREAD

**Issue by geertdoornbos** [danroth27/BlazorSSR#1]
Hi Dan, 

With the latest .net 8 and VS preview stuff installed, I can get the stream rendering to work when starting using ```dotnet run```. 

Starting from Visual Studio, stream rendering does not work. Response header for /fetchdata does not contain Transfer-Encoding: chunked. In your demo's, you started the app from Visual Studio. 

Did you change some VS settings?

**Comment by danroth27** [comment]
Hi @geertdoornbos. I'm also seeing that the `Transfer-Encoding: chunked` response header is sent when running the app using `dotnet run` but isn't sent when running from VS, but I still see the FetchData page behavior as expected. You should see the Loading... message and then one second later the weather data shows up. Are you seeing something different?

**Comment by geertdoornbos** [comment]
I don't see the Loading... message (when started from VS). When the page is loading, it takes a second, then the page becomes visible. 

Here's my network tab list:
![image](https://github.com/danroth27/BlazorSSR/assets/516775/a6289c81-a10e-4572-aa43-2ebe58f7d587)
Do you see the same sequence?

Do you have BrowserLink enabled in VS?

dotnet: 8.0.0
runtime: .NET 8.0.0-preview.4.23259.5
VS: Version 17.7.0 Preview 1.0

(delay set to 2 sec)
![image](https://github.com/danroth27/BlazorSSR/assets/516775/0119b2d0-329e-4712-9f42-999e48d82c5f)

In the request headers of /fetchdata I also see the first four :Authority: , :Method:, :Path: and :Scheme: headers when started from Visual Studio, not when started from ```dotnet run```
![image](https://github.com/danroth27/BlazorSSR/assets/516775/cec76c1b-001f-4676-98ae-65a7f84b9bda)

Same effect on Edge vs Chrome.

**Comment by danroth27** [comment]
> Do you have BrowserLink enabled in VS?

Nope, I didn't. When I enable CSS Hot Reload (which brings in browser link) I hit this issue as well. I'll follow up.

**Comment by danroth27** [comment]
Looks like this is a known issue that we are tracking here: https://github.com/dotnet/aspnetcore/issues/47608

**Comment by geertdoornbos** [comment]
That helped, thanks Dan!
